name: Build and deploy to Itch.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache LÖVE distribution
      id: cache-love
      uses: actions/cache@v4
      with:
        path: love-11.5-win64
        key: love-11.5-win64-v1

    - name: If LOVE distribution is not found, download
      if: steps.cache-love.outputs.cache-hit != 'true'
      run: |
        curl -L --output love.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
        7z x love.zip
    - name: Create .love file
      shell: cmd
      run: |
        dir /s /b
        7z a -tzip mygame.love . -xr!.git -xr!.github -xr!love-11.5-win64 -xr!*.zip

    - name: Create Windows executable
      shell: cmd
      run: |
        mkdir game-dist
        copy /b love-11.5-win64\love.exe+mygame.love game-dist\mygame.exe
        xcopy love-11.5-win64\*.dll game-dist\
        copy license.txt game-dist\
        del love-11.5-win64\love.exe
        del love-11.5-win64\lovec.exe
        cd game-dist
        7z a -tzip ..\mygame-windows.zip *

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: mygame-windows
        path: mygame-windows.zip

    - name: Download Butler
      shell: cmd
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
        mkdir butler
        7z x butler.zip -obutler
        butler\butler.exe version

    - name: Push to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        .\\butler\\butler.exe push game-dist chiichan-makes-game/ais-game:windows
        # Replace YOUR_ITCH_USERNAME with your itch.io username
        # Replace YOUR_GAME_NAME with your game's name on itch.io
