name: Build and deploy to Itch.io

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up zip
      run: |
        curl -L --output love.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
        7z x love.zip

    - name: Create .love file
      shell: cmd
      run: |
        7z a -tzip mygame.love . -xr!.git -xr!.github -xr!love-11.5-win64

    - name: Create Windows executable
      run: |
        copy /b love-11.5-win64\love.exe+mygame.love mygame.exe
        xcopy love-11.5-win64\*.dll .
        del love-11.5-win64\love.exe
        del love-11.5-win64\lovec.exe
        7z a -tzip mygame-windows.zip mygame.exe license.txt *.dll

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: mygame-windows
        path: mygame-windows.zip